import 'note.dart';

const Map<MusicalKey, Set<String>> keyNotesMap = {
  MusicalKey.C_Major: {'C', 'D', 'E', 'F', 'G', 'A', 'B'},
  MusicalKey.G_Major: {'G', 'A', 'B', 'C', 'D', 'E', 'F#'},
  MusicalKey.D_Major: {'D', 'E', 'F#', 'G', 'A', 'B', 'C#'},
  MusicalKey.A_Major: {'A', 'B', 'C#', 'D', 'E', 'F#', 'G#'},
  MusicalKey.E_Major: {'E', 'F#', 'G#', 'A', 'B', 'C#', 'D#'},
  MusicalKey.B_Major: {'B', 'C#', 'D#', 'E', 'F#', 'G#', 'A#'},
  MusicalKey.F_Sharp_Major: {'F#', 'G#', 'A#', 'B', 'C#', 'D#', 'E#'},
  MusicalKey.C_Sharp_Major: {'C#', 'D#', 'E#', 'F#', 'G#', 'A#', 'B#'},
  MusicalKey.F_Major: {'F', 'G', 'A', 'A#', 'C', 'D', 'E'},
  MusicalKey.Bb_Major: {'A#', 'C', 'D', 'D#', 'F', 'G', 'A'},
  MusicalKey.Eb_Major: {'D#', 'F', 'G', 'G#', 'A#', 'C', 'D'},
  MusicalKey.Ab_Major: {'G#', 'A#', 'C', 'C#', 'D#', 'F', 'G'},
  MusicalKey.Db_Major: {'C#', 'D#', 'F', 'F#', 'G#', 'A#', 'C'},
  MusicalKey.Gb_Major: {'F#', 'G#', 'A#', 'B', 'C#', 'D#', 'F'},
  MusicalKey.Cb_Major: {'B', 'C#', 'D#', 'E', 'F#', 'G#', 'A#'},
};

final List<ViolinNote> allNotes = [
  // G String
  const ViolinNote(
    baseName: 'G',
    octave: 3,
    solfege: 'Sol',
    frequency: 196.00,
    staffIndex: -5,
  ),
  const ViolinNote(
    baseName: 'G#',
    octave: 3,
    solfege: 'Sol#',
    frequency: 207.65,
    staffIndex: -5,
  ),
  const ViolinNote(
    baseName: 'A',
    octave: 3,
    solfege: 'La',
    frequency: 220.00,
    staffIndex: -4,
  ),
  const ViolinNote(
    baseName: 'A#',
    octave: 3,
    solfege: 'La#',
    frequency: 233.08,
    staffIndex: -4,
  ),
  const ViolinNote(
    baseName: 'B',
    octave: 3,
    solfege: 'Si',
    frequency: 246.94,
    staffIndex: -3,
  ),
  const ViolinNote(
    baseName: 'C',
    octave: 4,
    solfege: 'Do',
    frequency: 261.63,
    staffIndex: -2,
  ),
  const ViolinNote(
    baseName: 'C#',
    octave: 4,
    solfege: 'Do#',
    frequency: 277.18,
    staffIndex: -2,
  ),
  // D String
  const ViolinNote(
    baseName: 'D',
    octave: 4,
    solfege: 'Re',
    frequency: 293.66,
    staffIndex: -1,
  ),
  const ViolinNote(
    baseName: 'D#',
    octave: 4,
    solfege: 'Re#',
    frequency: 311.13,
    staffIndex: -1,
  ),
  const ViolinNote(
    baseName: 'E',
    octave: 4,
    solfege: 'Mi',
    frequency: 329.63,
    staffIndex: 0,
  ),
  const ViolinNote(
    baseName: 'F',
    octave: 4,
    solfege: 'Fa',
    frequency: 349.23,
    staffIndex: 1,
  ),
  const ViolinNote(
    baseName: 'F#',
    octave: 4,
    solfege: 'Fa#',
    frequency: 369.99,
    staffIndex: 1,
  ),
  const ViolinNote(
    baseName: 'G',
    octave: 4,
    solfege: 'Sol',
    frequency: 392.00,
    staffIndex: 2,
  ),
  const ViolinNote(
    baseName: 'G#',
    octave: 4,
    solfege: 'Sol#',
    frequency: 415.30,
    staffIndex: 2,
  ),
  // A String
  const ViolinNote(
    baseName: 'A',
    octave: 4,
    solfege: 'La',
    frequency: 440.00,
    staffIndex: 3,
  ),
  const ViolinNote(
    baseName: 'A#',
    octave: 4,
    solfege: 'La#',
    frequency: 466.16,
    staffIndex: 3,
  ),
  const ViolinNote(
    baseName: 'B',
    octave: 4,
    solfege: 'Si',
    frequency: 493.88,
    staffIndex: 4,
  ),
  const ViolinNote(
    baseName: 'C',
    octave: 5,
    solfege: 'Do',
    frequency: 523.25,
    staffIndex: 5,
  ),
  const ViolinNote(
    baseName: 'C#',
    octave: 5,
    solfege: 'Do#',
    frequency: 554.37,
    staffIndex: 5,
  ),
  const ViolinNote(
    baseName: 'D',
    octave: 5,
    solfege: 'Re',
    frequency: 587.33,
    staffIndex: 6,
  ),
  const ViolinNote(
    baseName: 'D#',
    octave: 5,
    solfege: 'Re#',
    frequency: 622.25,
    staffIndex: 6,
  ),
  // E String
  const ViolinNote(
    baseName: 'E',
    octave: 5,
    solfege: 'Mi',
    frequency: 659.25,
    staffIndex: 7,
  ),
  const ViolinNote(
    baseName: 'F',
    octave: 5,
    solfege: 'Fa',
    frequency: 698.46,
    staffIndex: 8,
  ),
  const ViolinNote(
    baseName: 'F#',
    octave: 5,
    solfege: 'Fa#',
    frequency: 739.99,
    staffIndex: 8,
  ),
  const ViolinNote(
    baseName: 'G',
    octave: 5,
    solfege: 'Sol',
    frequency: 783.99,
    staffIndex: 9,
  ),
  const ViolinNote(
    baseName: 'G#',
    octave: 5,
    solfege: 'Sol#',
    frequency: 830.61,
    staffIndex: 9,
  ),
  const ViolinNote(
    baseName: 'A',
    octave: 5,
    solfege: 'La',
    frequency: 880.00,
    staffIndex: 10,
  ),
  const ViolinNote(
    baseName: 'A#',
    octave: 5,
    solfege: 'La#',
    frequency: 932.33,
    staffIndex: 10,
  ),
  const ViolinNote(
    baseName: 'B',
    octave: 5,
    solfege: 'Si',
    frequency: 987.77,
    staffIndex: 11,
  ),
  const ViolinNote(
    baseName: 'C',
    octave: 6,
    solfege: 'Do',
    frequency: 1046.50,
    staffIndex: 12,
  ),
  const ViolinNote(
    baseName: 'C#',
    octave: 6,
    solfege: 'Do#',
    frequency: 1108.73,
    staffIndex: 12,
  ),
];
